### ISSUE TITLE
apache and php use flags

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/ganglion#9]
Output of
```
$ equery u www-servers/apache > /tmp/apache-use-flags.txt
$ equery u dev-lang/php > /tmp/php-use-flags.txt
```

[apache-use-flags.txt](https://github.com/zdavatz/ganglion/files/6217204/apache-use-flags.txt)
[php-use-flags.txt](https://github.com/zdavatz/ganglion/files/6217206/php-use-flags.txt)

**Comment by grauwoelfchen** [comment]
Danke!
